ECommerce/Models/Order.cs
using System;
using System.Collections.Generic;

namespace ECommerce.Models
{
    public partial class Order
    {
        public Order()
        {
            Dispute = new HashSet<Dispute>();
        }

        public int Id { get; set; }
        public string CustomerId { get; set; }
        public int ServiceId { get; set; }
        public string OrderStatus { get; set; }
        public DateTime OrderDate { get; set; }
        public int? Rating { get; set; }
        public string OrderNotes { get; set; }
        public string RatingNotes { get; set; }

        public AspNetUsers Customer { get; set; }
        public Service Service { get; set; }
        public ICollection<Dispute> Dispute { get; set; }
    }
}

ECommerce/Controllers/DisputesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ECommerce.Models;
using ECommerce.Repositories.Interfaces;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace ECommerce.Controllers
{
    public class DisputesController : Controller
    {
        private readonly IDispute disputeRepository;
        private readonly UserManager<ApplicationUser> _userManager;

        public DisputesController(IDispute disputeRepository, IOrder orderRepository, UserManager<ApplicationUser> _userManager)
        {
            this.disputeRepository = disputeRepository;
            this._userManager = _userManager;
        }
        [Authorize(Policy = "Admin_CustomerService")]

        // GET: Disputes
        public ActionResult Index()
        {
            var disputes = disputeRepository.List();
            return View(disputes);
        }
        [Authorize(Policy = "Customer")]

        // GET: DisputesByCostomer
        public ActionResult CustomerDisputes(string customerId)
        {
            var disputes = disputeRepository.List().Where(x=>x.Order.CustomerId == customerId);
            return View(disputes);
        }
        [Authorize(Policy = "ServiceProvider")]

        // GET: DisputesByCompany
        public ActionResult CompanyDisputes(string SproviderId)
        {
            var disputes = disputeRepository.List().Where(x=>x.Order.Service.Sprovider.User.Id == SproviderId);
            return View(disputes);
        }

        // GET: Disputes/Details/5
        public ActionResult Details(int id)
        {
            var dispute = disputeRepository.Find(id);

            return View(dispute);
        }
        [Authorize(Policy = "Customer")]

        // GET: Disputes/Create
        public ActionResult Create(int orderId, string customerId)
        {
            ViewBag.CustomerId = customerId;
            TempData["OrderId"] = orderId;
            return View();
        }
        [Authorize(Policy = "Customer")]

        // POST: Disputes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Dispute dispute)
        {
            dispute.OrderId = Int32.Parse(TempData["OrderId"].ToString());
            dispute.OpenedDate = DateTime.Now;
            dispute.Status = "Opened";
            if (ModelState.IsValid)
            {
                disputeRepository.Add(dispute);

                return RedirectToAction(nameof(CustomerDisputes), new { customerId = _userManager.GetUserId(HttpContext.User) });
            }
            return View();
        }

        public ActionResult TakeDispute(int id, string arbiterId)
        {
            var dispute = disputeRepository.Find(id);
            dispute.Status = "OnProgress";
            dispute.ArbiterId = arbiterId;
            disputeRepository.Update(id, dispute);

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Policy = "Admin_CustomerService")]

        // GET: Disputes/Edit/5
        public ActionResult Edit(int id)
        {
            var dispute = disputeRepository.Find(id);
            return View(dispute);
        }

        // POST: Disputes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Policy = "Admin_CustomerService")]

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind("Id,OrderId,OpenedDate,ArbiterId,Result,Status")] Dispute dispute)
        {
            if (ModelState.IsValid)
            {
                Dispute newDispute = disputeRepository.Find(id);

                newDispute.Result = dispute.Result;
                newDispute.Status = dispute.Status;

                disputeRepository.Update(id, newDispute);

                return RedirectToAction(nameof(Index));
            }
            return View(dispute);
        }


        // GET: Orders/Delete/5
        [Authorize(Policy = "Customer")]
        public ActionResult Delete(int id)
        {
            var dispute = disputeRepository.Find(id);
            if (dispute == null)
            {
                return NotFound();
            }

            return View(dispute);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Customer")]
        public ActionResult DeleteConfirmed(int id)
        {
            var dispute = disputeRepository.Find(id);
            disputeRepository.Delete(id);
            return RedirectToAction(nameof(CustomerDisputes), new { customerId = _userManager.GetUserId(HttpContext.User) });
        }

    }
}

ECommerce/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ECommerce.Models;
using ECommerce.Repositories.Interfaces;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Authorization;

namespace ECommerce.Controllers
{
    public class OrdersController : Controller
    {
       
        private readonly IOrder orderRepository;
        private readonly ISprovider sproviderRepository;

        public OrdersController(IOrder orderRepository, ISprovider sproviderRepository)
        {
            this.orderRepository = orderRepository;
            this.sproviderRepository = sproviderRepository;
        }

        public ActionResult Index()
        {
            var orders = orderRepository.List();
            return View(orders);
        }

        // GET: Orders
        [Authorize(Policy = "Customer")]
        public ActionResult CustomerOrders(string customerId)
        {
            var orders = orderRepository.List().Where(x=>x.CustomerId == customerId);

            return View(orders);
        }

        [Authorize(Policy = "ServiceProvider")]

        public ActionResult ServiceProviderOrders(string sproviderId)
        {
            var orders = orderRepository.List().Where(x => x.Service.Sprovider.User.Id == sproviderId);

            return View(orders);
        }

        // GET: Orders/Details/5
        public ActionResult Details(int id)
        {          
            var order =  orderRepository.Find(id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        [Authorize(Policy = "Customer")]
        public ActionResult Create(int myServiceID)
        {
            TempData["ServiceID"] = myServiceID;
            return View();
        }

        // POST: Orders/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Customer")]
        public ActionResult Create(Order order)
        {
            order.OrderDate = DateTime.Now;
            order.Rating = 0;
            order.RatingNotes = "";
            order.ServiceId = (int)TempData["ServiceID"];
            order.OrderStatus = "Opened";
            order.CustomerId = HttpContext.User.Identity.GetUserId();

            if (ModelState.IsValid)
            {
                orderRepository.Add(order);
                return RedirectToAction(nameof(CustomerOrders), new { customerId = order.CustomerId });
            }

            return View();
        }

        // GET: Orders/Edit/5
        //[Authorize(Policy = "ServiceProvider")]
        public ActionResult Edit(int id)
        {      
            var order = orderRepository.Find(id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize(Policy = "ServiceProvider")]
        public ActionResult Edit(int id, Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }
            var oldOrder = orderRepository.Find(id);
            if (order.OrderStatus != null)
            {
                oldOrder.OrderStatus = order.OrderStatus;
                if (ModelState.IsValid)
                {
                    orderRepository.Update(id, oldOrder);
                    return RedirectToAction(nameof(ServiceProviderOrders), new { sproviderId = oldOrder.Service.Sprovider.UserId });
                }
            }
            else if (order.OrderNotes != null)
            {
                oldOrder.OrderNotes = order.OrderNotes;
                if (ModelState.IsValid)
                {
                    orderRepository.Update(id, oldOrder);
                    return RedirectToAction(nameof(CustomerOrders), new { customerId = oldOrder.CustomerId });
                }
            }

       
            return View(order);
        }

        // GET: Orders/Rate/5
        [Authorize(Policy = "Customer")]
        public ActionResult Rate(int id)
        {
            var order = orderRepository.Find(id);
            order.Rating /= 20;

            return View(order);
        }

        // POST: Orders/Rate/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Customer")]
        public ActionResult Rate(int id, Order order)
        {

            var oldOrder = orderRepository.Find(id);
      
            oldOrder.Rating = order.Rating*20;
            oldOrder.RatingNotes = order.RatingNotes;
            if (ModelState.IsValid)
            {
                orderRepository.Update(id, oldOrder);
                //Start serviceProvider Rating
                var sprovider = oldOrder.Service.Sprovider;
                var ordersRating = orderRepository.List().Where(s => s.Rating > 0).Select(s => s.Rating);
                sprovider.Rating = 0;
                foreach (var item in ordersRating)
                {
                    sprovider.Rating += item;
                }
                sprovider.Rating = sprovider.Rating / ordersRating.Count();
                sproviderRepository.Update(sprovider.Id, sprovider);
                //End serviceProvider Rating

                return RedirectToAction(nameof(CustomerOrders), new { customerId = oldOrder.CustomerId });
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        [Authorize(Policy = "Customer")]
        public ActionResult Delete(int id)
        {
            var order = orderRepository.Find(id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Customer")]
        public ActionResult DeleteConfirmed(int id)
        {
            var order = orderRepository.Find(id);
            orderRepository.Delete(id);
            return RedirectToAction(nameof(CustomerOrders));
        }
    }
}

ECommerce/Views/Orders/Create.cshtml
@model ECommerce.Models.Order

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>


            <div class="form-group">
                <label asp-for="OrderNotes" class="control-label"></label>
                <input asp-for="OrderNotes" class="form-control" />
                <span asp-validation-for="OrderNotes" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ECommerce/Views/Orders/CustomerOrders.cshtml
@model IEnumerable<ECommerce.Models.Order>

@{
    ViewData["Title"] = "Customer Orders";
}

<h2>Customer Orders</h2>
<br />

<table class="table table-striped table-bordered table-responsive">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Service.Sprovider.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Service)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderDate)
            </th>
            <th width="18%">
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderStatus)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Service.Sprovider.CompanyName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Service.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderDate)
                </td>
                <td>
                    <div style="margin: auto; width:50%;">
                        @*<span>Rate: </span>*@
                        @{
                            var counter = 0;
                            for (int i = 0; i < item.Rating; i += 20)
                            {
                                counter++;
                                <i class="fa fa-star" style="color:goldenrod; align-content:center"></i>
                            }
                            for (int i = 0; i < 5 - counter; i++)
                            {
                                <i class="fa fa-star"></i>
                            }
                        }
                    </div>
                </td>
                <td>
                    @if (item.OrderStatus == "Opened")
                    {
                        <p class="btn btn-primary disabled">@item.OrderStatus</p>
                    }
                    else if (item.OrderStatus == "Closed")
                    {
                        <p class="btn btn-success disabled">@item.OrderStatus</p>
                    }
                    else if (item.OrderStatus == "Rejected")
                    {
                        <p class="btn btn-danger disabled">@item.OrderStatus</p>
                    }
                </td>
                <td>
                    <a asp-action="Rate" asp-route-id="@item.Id">Rate</a> |
                    <a asp-action="Create" asp-controller="Disputes" asp-route-orderId="@item.Id" asp-route-CustomerId="@item.CustomerId">Open Complaint</a> |
                    @if (item.OrderStatus=="Opened")
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a><span> | </span>
                    }
                  
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

ECommerce/Views/Orders/Delete.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ECommerce.Models.ApplicationUser> UserManager
@model ECommerce.Models.Order

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <br />

    @*Order*@
    <table class="table table-bordered table-striped table-responsive">
        <thead>
            <tr>
                <th colspan="4">
                    Order
                </th>
            </tr>
        </thead>
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Date
                </th>
                <th>
                    Notes
                </th>
                <th>
                    Status
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Model.Id
                </td>
                <td>
                    @Model.OrderDate
                </td>
                <td>
                    @Model.OrderNotes
                </td>
                <td>
                    @Model.OrderStatus
                </td>
            </tr>
        </tbody>
    </table>

    <br />
    <br />

    @*Service Provider*@
    <table class="table table-bordered table-striped table-responsive">
        <thead>
            <tr>
                <th colspan="5">
                    Service Provider: @Model.Service.Sprovider.CompanyName
                </th>
            </tr>
        </thead>
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Phone Number
                </th>
                <th>
                    Email
                </th>
                <th>
                    Address
                </th>
                <th>
                    Image
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Model.Service.Sprovider.User.FullName
                </td>
                <td>
                    @Model.Service.Sprovider.User.PhoneNumber
                </td>
                <td>
                    @Model.Service.Sprovider.User.Email
                </td>
                <td>
                    @Model.Service.Sprovider.User.Address
                </td>
                <td>
                    <img src="~/uploads/sprovider/@Model.Service.Sprovider.Image" alt="@Model.Service.Sprovider.CompanyName" style="width:160px; height:160px;" class="img-thumbnail" />
                </td>
            </tr>
        </tbody>
    </table>

    <br />
    <br />

    @*Service*@
    <table class="table table-bordered table-striped table-responsive">
        <thead>
            <tr>
                <th colspan="4">
                    Service
                </th>
            </tr>
        </thead>
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Phone Number
                </th>
                <th>
                    ExpectedTime
                </th>
                <th>
                    Image
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Model.Service.Name
                </td>
                <td>
                    @Model.Service.Description
                </td>
                <td>
                    @Model.Service.ExpectedTime
                </td>
                <td>
                    <img src="~/uploads/service/@Model.Service.Image" alt="@Model.Service.Name" style="width:160px; height:160px;" class="img-thumbnail" />
                </td>
            </tr>
        </tbody>
    </table>

    <br />
    <br />

    @*Customer*@
    <table class="table table-bordered table-striped table-responsive">
        <thead>
            <tr>
                <th colspan="4">
                    Customer
                </th>
            </tr>
        </thead>
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Phone Number
                </th>
                <th>
                    Email
                </th>
                <th>
                    Address
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Model.Customer.FullName
                </td>
                <td>
                    @Model.Customer.PhoneNumber
                </td>
                <td>
                    @Model.Customer.Email
                </td>
                <td>
                    @Model.Customer.Address
                </td>
            </tr>
        </tbody>
    </table>


    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="CustomerOrders" asp-route-customerId="@UserManager.GetUserId(User)">Back to List</a>
    </form>
</div>

ECommerce/Views/Orders/Details.cshtml
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Identity
@inject IAuthorizationService AuthorizationService
@inject UserManager<ECommerce.Models.ApplicationUser> UserManager

@model ECommerce.Models.Order

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

@*Order*@
<table class="table table-bordered table-striped table-responsive">
    <thead>
        <tr>
            <th colspan="4">
                Order
            </th>
        </tr>
    </thead>
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Date
            </th>
            <th>
                Notes
            </th>
            <th>
                Status
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Model.Id
            </td>
            <td>
                @Model.OrderDate
            </td>
            <td>
                @Model.OrderNotes
            </td>
            <td>
                @Model.OrderStatus
            </td>
        </tr>
    </tbody>
</table>

<br />
<br />

@if (!(await AuthorizationService.AuthorizeAsync(User, "Customer")).Succeeded)
{
    @*Service Provider*@
    <table class="table table-bordered table-striped table-responsive">
        <thead>
            <tr>
                <th colspan="4">
                    Service Provider Manager
                </th>
            </tr>
        </thead>
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Phone Number
                </th>
                <th>
                    Email
                </th>
                <th>
                    Address
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Model.Service.Sprovider.User.FullName
                </td>
                <td>
                    @Model.Service.Sprovider.User.PhoneNumber
                </td>
                <td>
                    @Model.Service.Sprovider.User.Email
                </td>
                <td>
                    @Model.Service.Sprovider.User.Address
                </td>
            </tr>
        </tbody>
    </table>

    <br />
    <br />

}

@*Company*@
<table class="table table-bordered table-striped table-responsive">
    <thead>
        <tr>
            <th colspan="4">
                Service Provider
            </th>
        </tr>
    </thead>
    <thead>
        <tr>
            <th>
                Category
            </th>
            <th>
                Name
            </th>
            <th>
                Rating
            </th>
            <th>
                Image
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Model.Service.Sprovider.Category.Name
            </td>
            <td>
                @Model.Service.Sprovider.CompanyName
            </td>
            <td>
                <div style="margin: auto; width:50%;">
                    @*<span>Rate: </span>*@
                    @{
                        var counter = 0;
                        for (int i = 0; i < Model.Rating; i += 20)
                        {
                            counter++;
                            <i class="fa fa-star" style="color:goldenrod; align-content:center"></i>
                        }
                        for (int i = 0; i < 5 - counter; i++)
                        {
                            <i class="fa fa-star"></i>
                        }
                    }
                </div>
            </td>
            <td>
                <img src="~/uploads/sprovider/@Model.Service.Sprovider.Image" alt="@Model.Service.Sprovider.CompanyName" style="width:160px; height:160px;" class="img-thumbnail" />
            </td>
        </tr>
    </tbody>
</table>
<br />
<br />

@*Service*@
<table class="table table-bordered table-striped table-responsive">
    <thead>
        <tr>
            <th colspan="4">
                Service
            </th>
        </tr>
    </thead>
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Phone Number
            </th>
            <th>
                ExpectedTime
            </th>
            <th>
                Image
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Model.Service.Name
            </td>
            <td>
                @Model.Service.Description
            </td>
            <td>
                @Model.Service.ExpectedTime
            </td>
            <td>
                <img src="~/uploads/service/@Model.Service.Image" alt="@Model.Service.Name" style="width:160px; height:160px;" class="img-thumbnail" />
            </td>
        </tr>
    </tbody>
</table>

<br />
<br />

@*Customer*@
<table class="table table-bordered table-striped table-responsive">
    <thead>
        <tr>
            <th colspan="4">
                Customer
            </th>
        </tr>
    </thead>
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Phone Number
            </th>
            <th>
                Email
            </th>
            <th>
                Address
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Model.Customer.FullName
            </td>
            <td>
                @Model.Customer.PhoneNumber
            </td>
            <td>
                @Model.Customer.Email
            </td>
            <td>
                @Model.Customer.Address
            </td>
        </tr>
    </tbody>
</table>


@if ((await AuthorizationService.AuthorizeAsync(User, "Customer")).Succeeded)
{
    <a asp-controller="Orders" asp-action="CustomerOrders" asp-route-customerId="@UserManager.GetUserId(User)">Back to List</a>
}
else if ((await AuthorizationService.AuthorizeAsync(User, "ServiceProvider")).Succeeded)
{
    <a asp-controller="Orders" asp-action="ServiceProviderOrders" asp-route-SproviderId="@UserManager.GetUserId(User)">Back to List</a>
}
else if ((await AuthorizationService.AuthorizeAsync(User, "Admin_CustomerService")).Succeeded)
{
    <a asp-controller="Orders" asp-action="Index">Back to List</a>
}
<div>
</div>

ECommerce/Views/Orders/Edit.cshtml
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Identity
@inject IAuthorizationService AuthorizationService
@inject UserManager<ECommerce.Models.ApplicationUser> UserManager

@model ECommerce.Models.Order

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            @if ((await AuthorizationService.AuthorizeAsync(User, "Customer")).Succeeded)
            {
                <div class="form-group">
                    <label asp-for="OrderNotes" class="control-label"></label>
                    <input asp-for="OrderNotes" class="form-control" />
                    <span asp-validation-for="OrderNotes" class="text-danger"></span>
                </div>
            }
            else if ((await AuthorizationService.AuthorizeAsync(User, "ServiceProvider")).Succeeded)
            {
                <div class="form-group">
                    <label asp-for="OrderStatus" class="control-label"></label>
                    <select asp-for="OrderStatus" class="form-control">
                        <option value="Opened">Opened</option>
                        <option value="Closed">Closed</option>
                        <option value="Rejected">Rejected</option>

                    </select>
                    <span asp-validation-for="OrderStatus" class="text-danger"></span>
                </div>
            }
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @if ((await AuthorizationService.AuthorizeAsync(User, "Customer")).Succeeded)
    {
        <a asp-controller="Orders" asp-action="CustomerOrders" asp-route-customerId="@UserManager.GetUserId(User)">Back to List</a>
    }
    else if ((await AuthorizationService.AuthorizeAsync(User, "ServiceProvider")).Succeeded)
    {
        <a asp-controller="Orders" asp-action="ServiceProviderOrders" asp-route-SproviderId="@UserManager.GetUserId(User)">Back to List</a>
    }
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ECommerce/Views/Orders/Rate.cshtml
@model ECommerce.Models.Order

@{
    ViewData["Title"] = "Rate";
}

<h2>Rate</h2>

<h4>Order</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Rate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="ServiceId" />
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input class="form-control" asp-for="Rating" type="range" id="vol"  min="1" max="5">
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RatingNotes" class="control-label"></label>
                <input asp-for="RatingNotes" class="form-control" />
                <span asp-validation-for="RatingNotes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Rate" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="CustomerOrders" asp-route-customerId="@Model.CustomerId">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}