ECommerce/Models/Sprovider.cs
using System;
using System.Collections.Generic;

namespace ECommerce.Models
{
    public partial class Sprovider
    {
        public Sprovider()
        {
            Service = new HashSet<Service>();
        }

        public int Id { get; set; }
        public string UserId { get; set; }
        public string CompanyName { get; set; }
        public int? Rating { get; set; }
        public string Image { get; set; }
        public int CategoryId { get; set; }

        public Category Category { get; set; }
        public AspNetUsers User { get; set; }
        public ICollection<Service> Service { get; set; }
    }
}

ECommerce/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ECommerce.Models;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNet.Identity;
using ECommerce.Repositories.Interfaces;
using Microsoft.AspNetCore.Authorization;
using ECommerce.Models.ViewModels;

namespace ECommerce.Controllers
{
    public class ServicesController : Controller
    {
        private readonly IService serviceRepository;
        private readonly ISprovider sproviderRepository;
        private readonly IHostingEnvironment hostingEnvironment;

        public ServicesController( IService serviceRepository, ISprovider sproviderRepository, IHostingEnvironment hostingEnvironment)
        {
            this.serviceRepository = serviceRepository;
            this.sproviderRepository = sproviderRepository;
            this.hostingEnvironment = hostingEnvironment;
        }

        // GET: Services
        [Authorize(Policy = "ServiceProvider")]
        public ActionResult Index(int SproviderId)
        {
            var Services = serviceRepository.List().Where(x => x.Sprovider.Id == SproviderId);
            return View(Services);
        }


        public ActionResult CompanyServices(int SproviderId)
        {
            var Services = serviceRepository.List().Where(x => x.Sprovider.Id == SproviderId);
            return View(Services);
        }

        // GET: Services/Details/5
        public ActionResult Details(int id)
        {
            var service = serviceRepository.Find(id);
            if (service == null)
            {
                return NotFound();
            }
            return View(service);
        }

        // GET: Services/Create
        [Authorize(Policy = "ServiceProvider")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Services/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "ServiceProvider")]
        public async Task<ActionResult> Create(ServiceViewModel serviceViewModel)
        {
            if (ModelState.IsValid)
            {
                string UrlImage = "";
                var files = HttpContext.Request.Form.Files;
                foreach (var Image in files)
                {
                    if (Image != null && Image.Length > 0)
                    {
                        var file = Image;

                        var uploads = Path.Combine(hostingEnvironment.WebRootPath, "uploads/service");
                        if (file.Length > 0)
                        {
                            // var fileName = Guid.NewGuid().ToString().Replace("-", "") + Path.GetExtension(file.FileName);
                            var fileName = Guid.NewGuid().ToString().Replace("-", "") + file.FileName;
                            using (var fileStream = new FileStream(Path.Combine(uploads, fileName), FileMode.Create))
                            {
                                await file.CopyToAsync(fileStream);
                                UrlImage = fileName;
                            }
                        }
                    }
                }

                var UserId = HttpContext.User.Identity.GetUserId();
                var SproviderId = sproviderRepository.List().Where(x => x.UserId == UserId).FirstOrDefault().Id;
                Service service = new Service
                {
                    Id = serviceViewModel.Id,
                    Image = UrlImage,
                    Name = serviceViewModel.Name,
                    Description = serviceViewModel.Description,
                    Price = serviceViewModel.Price,
                    ExpectedTime = serviceViewModel.ExpectedTime,
                    SproviderId = SproviderId
                };
                serviceRepository.Add(service);

                return RedirectToAction(nameof(Index), new { SproviderId = SproviderId });
            }
            return View();
        }

        [Authorize(Policy = "ServiceProvider")]
        // GET: Services/Edit/5
        public ActionResult Edit(int id)
        {
            var service = serviceRepository.Find(id);
            if (service == null)
            {
                return NotFound();
            }
            ViewData["SproviderId"] = new SelectList(sproviderRepository.List(), "Id", "CompanyName");
            return View(service);
        }

        [Authorize(Policy = "ServiceProvider")]
        // POST: Services/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Service service)
        {
            if (ModelState.IsValid)
            {
                string UrlImage = "";
                var files = HttpContext.Request.Form.Files;
                foreach (var Image in files)
                {
                    if (Image != null && Image.Length > 0)
                    {
                        var file = Image;

                        var uploads = Path.Combine(hostingEnvironment.WebRootPath, "uploads/service");
                        if (file.Length > 0)
                        {
                            // var fileName = Guid.NewGuid().ToString().Replace("-", "") + Path.GetExtension(file.FileName);
                            var fileName = Guid.NewGuid().ToString().Replace("-", "") + file.FileName;
                            using (var fileStream = new FileStream(Path.Combine(uploads, fileName), FileMode.Create))
                            {
                                await file.CopyToAsync(fileStream);
                                UrlImage = fileName;
                            }
                        }
                    }
                }
                Service newService = serviceRepository.Find(id);

                if (UrlImage != "")
                {
                    var Directory = Path.Combine(hostingEnvironment.WebRootPath, "uploads/service");
                    var fullPath = Path.Combine(Directory, newService.Image);
                    if (System.IO.File.Exists(fullPath))
                    {
                        System.IO.File.Delete(fullPath);
                    }
                    newService.Image = UrlImage;
                }
                newService.Description = service.Description;
                newService.Name = service.Name;
                newService.Price = service.Price;
                newService.ExpectedTime = service.ExpectedTime;

                serviceRepository.Update(id, newService);

                return RedirectToAction(nameof(Index), new { SproviderId = newService.SproviderId });
            }
            ViewData["SproviderId"] = new SelectList(sproviderRepository.List(), "Id", "CompanyName");
            return View(service);
        }


        // GET: Services/Delete/5
        public ActionResult Delete(int id)
        {
            var service = serviceRepository.Find(id);

            return View(service);
        }

        // POST: Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var service = serviceRepository.Find(id);
            var Directory = Path.Combine(hostingEnvironment.WebRootPath, "uploads/service");
            var fullPath = Path.Combine(Directory, service.Image);
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
            }
            serviceRepository.Delete(id);
            return RedirectToAction(nameof(Index), new { SproviderId = service.SproviderId });
        }
    }
}

ECommerce/Controllers/SprovidersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ECommerce.Models;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using ECommerce.Repositories.Interfaces;

namespace ECommerce.Controllers
{
    public class SprovidersController : Controller
    {
        private readonly ISprovider sproviderRepository;
        private readonly ICategory categoryRepository;
        private readonly IHostingEnvironment hostingEnvironment;

        public SprovidersController(ISprovider sproviderRepository, ICategory categoryRepository, IHostingEnvironment hostingEnvironment)
        {
            this.sproviderRepository = sproviderRepository;
            this.categoryRepository = categoryRepository;
            this.hostingEnvironment = hostingEnvironment;
        }

        // GET: Sproviders
        [Authorize(Policy = "Admin_CustomerService")]
        public ActionResult Index()
        {
            var sproviders = sproviderRepository.List();
            return View(sproviders);
        }
        public ActionResult CategoryCompanies(int catId)
        {
            var sProviders = sproviderRepository.List().Where(x => x.CategoryId == catId);
            ViewBag.category = categoryRepository.Find(catId);
            return View(sProviders);
        }

        // GET: Sproviders/Details/5
        [Authorize(Policy = "Admin_CustomerService")]
        public ActionResult Details(int id)
        {
            var sprovider = sproviderRepository.Find(id);
            if (sprovider == null)
            {
                return NotFound();
            }
            return View(sprovider);
        }

        // GET: Sproviders/Edit/5
        [Authorize(Policy = "Admin_CustomerService")]
        public ActionResult Edit(int id)
        {
            Sprovider sprovider = sproviderRepository.Find(id);
            ViewData["CategoryId"] = new SelectList(categoryRepository.List(), "Id", "Name", sprovider.CategoryId);
            //ViewData["UserId"] = new SelectList(categoryRepository.List(), "Id", "Id", sprovider.UserId);
            return View(sprovider);
        }

        // POST: Sproviders/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Sprovider sprovider)
        {
            if (ModelState.IsValid)
            {
                string UrlImage = "";
                var files = HttpContext.Request.Form.Files;
                foreach (var Image in files)
                {
                    if (Image != null && Image.Length > 0)
                    {
                        var file = Image;

                        var uploads = Path.Combine(hostingEnvironment.WebRootPath, "uploads/sprovider");
                        if (file.Length > 0)
                        {
                            // var fileName = Guid.NewGuid().ToString().Replace("-", "") + Path.GetExtension(file.FileName);
                            var fileName = Guid.NewGuid().ToString().Replace("-", "") + file.FileName;
                            using (var fileStream = new FileStream(Path.Combine(uploads, fileName), FileMode.Create))
                            {
                                await file.CopyToAsync(fileStream);
                                UrlImage = fileName;
                            }
                        }
                    }
                }
                Sprovider newSprovider = sproviderRepository.Find(id);
                if (UrlImage != "")
                {
                    var Directory = Path.Combine(hostingEnvironment.WebRootPath, "uploads/sprovider");
                    var fullPath = Path.Combine(Directory, newSprovider.Image);
                    if (System.IO.File.Exists(fullPath))
                    {
                        System.IO.File.Delete(fullPath);
                    }
                    newSprovider.Image = UrlImage;
                }
                newSprovider.CompanyName = sprovider.CompanyName;
                newSprovider.CategoryId = sprovider.CategoryId;

                sproviderRepository.Update(id, newSprovider);

                return RedirectToAction(nameof(Index));
            }
            return View(sprovider);
        }

        // GET: Sproviders/Delete/5
        public ActionResult Delete(int id)
        {
            var sprovider = sproviderRepository.Find(id);

            return View(sprovider);
        }

        // POST: Sproviders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                var sprovider = sproviderRepository.Find(id);
                var Directory = Path.Combine(hostingEnvironment.WebRootPath, "uploads/sprovider");
                var fullPath = Path.Combine(Directory, sprovider.Image);
                if (System.IO.File.Exists(fullPath))
                {
                    System.IO.File.Delete(fullPath);
                }
                sproviderRepository.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ECommerce/Views/Sproviders/CategoryCompanies.cshtml
@model IEnumerable<ECommerce.Models.Sprovider>

@{
    ViewData["Title"] = "Category Companies";
}
<br />
<br />
<div class="panel panel-default">
    <div class="panel-heading"><h2>@ViewBag.category.Name</h2></div>
    <div class="row panel-body" style="padding-left:40px;">
        <h4>@ViewBag.category.Description</h4>
        @foreach (var item in Model)
        {
            <div class="col-md-3 thumbnail" style="height: 280px; width: 250px; margin: 10px; ">
                <a asp-controller="Services" asp-action="CompanyServices" asp-route-SproviderId="@item.Id" style="text-decoration:none;color:black">
                    <img src="~/uploads/sprovider/@item.Image" style="height:175px; width:200px;" />
                    <h3 style="text-align:center">@Html.DisplayFor(modelItem => item.CompanyName)</h3>
                </a>
                <div style="margin: auto; width:50%;">
                    @*<span>Rate: </span>*@
                    @{
                        var counter = 0;
                        for (int i = 0; i < item.Rating; i += 20)
                        {
                            counter++;
                            <i class="fa fa-star" style="color:goldenrod; align-content:center"></i>
                        }
                        for (int i = 0; i < 5 - counter; i++)
                        {
                            <i class="fa fa-star" ></i>
                        }
                    }
                </div>
            </div>
        }
    </div>
</div>

ECommerce/Views/Sproviders/Delete.cshtml
@model ECommerce.Models.Sprovider

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sprovider</h4>
    <hr />
    @*Service Provider*@
    <table class="table table-bordered table-striped table-responsive">
        <thead>
            <tr>
                <th colspan="4">
                    Service Provider Manager
                </th>
            </tr>
        </thead>
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Phone Number
                </th>
                <th>
                    Email
                </th>
                <th>
                    Address
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Model.User.FullName
                </td>
                <td>
                    @Model.User.PhoneNumber
                </td>
                <td>
                    @Model.User.Email
                </td>
                <td>
                    @Model.User.Address
                </td>
            </tr>
        </tbody>
    </table>
    <br />
    <br />

    @*Company*@
    <table class="table table-bordered table-striped table-responsive">
        <thead>
            <tr>
                <th colspan="4">
                    Service Provider
                </th>
            </tr>
        </thead>
        <thead>
            <tr>
                <th>
                    Category
                </th>
                <th>
                    Name
                </th>
                <th>
                    Rating
                </th>
                <th>
                    Image
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Model.Category.Name
                </td>
                <td>
                    @Model.CompanyName
                </td>
                <td>
                    <div style="margin: auto; width:50%;">
                        @*<span>Rate: </span>*@
                        @{
                            var counter = 0;
                            for (int i = 0; i < Model.Rating; i += 20)
                            {
                                counter++;
                                <i class="fa fa-star" style="color:goldenrod; align-content:center"></i>
                            }
                            for (int i = 0; i < 5 - counter; i++)
                            {
                                <i class="fa fa-star"></i>
                            }
                        }
                    </div>
                </td>
                <td>
                    <img src="~/uploads/sprovider/@Model.Image" alt="@Model.CompanyName" style="width:160px; height:160px;" class="img-thumbnail" />
                </td>
            </tr>
        </tbody>
    </table>



    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ECommerce/Views/Sproviders/Details.cshtml
@model ECommerce.Models.Sprovider

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Sprovider</h4>

    @*Service Provider*@
    <table class="table table-bordered table-striped table-responsive">
        <thead>
            <tr>
                <th colspan="4">
                    Service Provider Manager
                </th>
            </tr>
        </thead>
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Phone Number
                </th>
                <th>
                    Email
                </th>
                <th>
                    Address
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Model.User.FullName
                </td>
                <td>
                    @Model.User.PhoneNumber
                </td>
                <td>
                    @Model.User.Email
                </td>
                <td>
                    @Model.User.Address
                </td>
            </tr>
        </tbody>
    </table>
    <br />
    <br />

    @*Company*@
    <table class="table table-bordered table-striped table-responsive">
        <thead>
            <tr>
                <th colspan="4">
                    Service Provider
                </th>
            </tr>
        </thead>
        <thead>
            <tr>
                <th>
                    Category
                </th>
                <th>
                    Name
                </th>
                <th>
                    Rating
                </th>
                <th>
                    Image
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Model.Category.Name
                </td>
                <td>
                    @Model.CompanyName
                </td>
                <td>
                    <div style="margin: auto; width:50%;">
                        @*<span>Rate: </span>*@
                        @{
                            var counter = 0;
                            for (int i = 0; i < Model.Rating; i += 20)
                            {
                                counter++;
                                <i class="fa fa-star" style="color:goldenrod; align-content:center"></i>
                            }
                            for (int i = 0; i < 5 - counter; i++)
                            {
                                <i class="fa fa-star"></i>
                            }
                        }
                    </div>
                </td>
                <td>
                    <img src="~/uploads/sprovider/@Model.Image" alt="@Model.CompanyName" style="width:160px; height:160px;" class="img-thumbnail" />
                </td>
            </tr>
        </tbody>
    </table>




</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ECommerce/Views/Sproviders/Edit.cshtml
@model ECommerce.Models.Sprovider

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Sprovider</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Sproviders" asp-action="Edit" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyName" class="control-label"></label>
                <input asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input type="file" asp-for="Image" class="form-control changeImage" />
                <span asp-validation-for="Image" class="text-danger"></span>
                <br />
                <div style="width:160px; height:160px;" class="table table-bordered">
                    <img src="~/uploads/sprovider/@Model.Image" alt="@Model.Image" style="width:160px; height:160px;" class="change_edit img-thumbnail" />
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script src="~/js/jquery-3.5.1.min.js"></script>
<script type="text/javascript">
        $(function(){
                  $('.changeImage').change(function(){
                    var input = this;
                    var url = $(this).val();
                    var ext = url.substring(url.lastIndexOf('.') + 1).toLowerCase();
                        if (input.files && input.files[0]&& (ext == "gif" || ext == "png" || ext == "jpeg" || ext == "jpg"))
                         {
                            var reader = new FileReader();

                            reader.onload = function (e)
                            {
                               $('.change_edit').attr('src', e.target.result);
                            }
                           reader.readAsDataURL(input.files[0]);
                        }
                        else
                        {
                            $('.change_edit').attr('src', '/uploads/@Model.Image');
                        }
                });
        });
</script>

ECommerce/Views/Sproviders/Index.cshtml
@model IEnumerable<ECommerce.Models.Sprovider>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-area="Identity" asp-page="/Account/Registersprovider">Create New</a>
</p>
<table class="table table-striped table-bordered table-responsive">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Category)

            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyName)

            </th>

            <th>
                @Html.DisplayNameFor(model => model.Rating)

            </th>
            <th>
                Manager
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)

            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyName)
                </td>

                <td>
                    <div style="margin: auto; width:50%;">
                        @*<span>Rate: </span>*@
                        @{
                            var counter = 0;
                            for (int i = 0; i < item.Rating; i += 20)
                            {
                                counter++;
                                <i class="fa fa-star" style="color:goldenrod; align-content:center"></i>
                            }
                            for (int i = 0; i < 5 - counter; i++)
                            {
                                <i class="fa fa-star"></i>
                            }
                        }
                    </div>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.User.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.User.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.User.PhoneNumber)
                </td>
                <td>
                    <img src="~/uploads/sprovider/@item.Image" alt="@item.CompanyName" style="width:160px; height:160px;" class="img-thumbnail" />
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>